### ISSUE TITLE
Unhandled rejection process.send

### ISSUE THREAD

**Issue by mrmlnc** [sindresorhus/ava#116]
After update to 0.3.0 get error:

Version Node.js: 4.2.1
Version NPM: 2.14.7
OS: Windows 10 & Linux
Travis CI link: https://travis-ci.org/mrmlnc/grunt-assetser/builds/88578638

Test file:
```js
var fs = require('fs');
var test = require('ava');

test('default space', function(t) {
  var actual = fs.readFileSync('tmp/default.html');
  var expected = fs.readFileSync('test/expected/default.html');
  t.is(actual, expected);
  t.end();
});

test('default tab', function(t) {
  var actual = fs.readFileSync('tmp/default_tab.html');
  var expected = fs.readFileSync('test/expected/default_tab.html');
  t.is(actual, expected);
  t.end();
});
```

Console:
```js
Unhandled rejection TypeError: process.send is not a function
    at exit (/home/travis/build/mrmlnc/grunt-assetser/node_modules/ava/index.js:55:10)
    at tryCatcher (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/mrmlnc/grunt-assetser/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by vdemedes** [comment]
AVA 0.3.0 removed support for `node test.js`, now you have to use `ava` CLI to run your tests: `ava test.js`. Let me know if it works.

**Comment by mrmlnc** [comment]
@vdemedes Yeap, it works! :+1:

**Comment by Ivan-Feofanov** [comment]
I have the same error when use gulp-ava package

**Comment by vdemedes** [comment]
@Ivan-Feofanov See https://github.com/sindresorhus/ava/issues/116#issuecomment-152780353

**Comment by vdemedes** [comment]
@Ivan-Feofanov Could you please open a new issue with a more detailed description?
